add base_namespace config value and use it for Mailable instanciation
spatie/laravel-mailable-test pull request #13
Opened 2017-06-14 11:12 UTC by fetzi

fixes #12

2017-06-14 11:22 UTC, freekmurze requested changes
Thank you for this. Could you take care of these comments?

2017-06-14 11:22 UTC, freekmurze commented on src/SendTestMail.php
> +        if (! $this->vaildateMailable($this->argument('mailableClass'))) {
Typo in function name

2017-06-14 11:22 UTC, freekmurze commented on config/mailable-test.php
> +     * base namespace Mailable classes
Make the first character a capital

2017-06-14 11:22 UTC, freekmurze commented on src/MailableFactory.php
> +                throw MailableDoesntExist::withClass($mailableClass);
Rename to `MailableDoesNotExist`

2017-06-14 11:22 UTC, freekmurze commented on tests/SendTestMailTest.php
> +        Config::set('mailable-test.base_namespace', 'Spatie\\MailableTest\\Test');
Use `config` function instead of the facade.

2017-06-14 11:22 UTC, freekmurze commented on tests/SendTestMailTest.php
> +        Config::set('mailable-test.base_namespace', 'Spatie\\MailableTest\\Test');
Preferably users shouldn't have to type double slashes in the config file. Could change this line to

```
config('mailable-test.base_namespace', Spatie\MailableTest\Test::class);
```

and make sure the test passes.

2017-06-14 11:22 UTC, freekmurze commented on README.md
> +    'base_namespace' => 'App\\Mails',
Could you make sure this option will work without users having to type double slashes?

2017-06-14 12:02 UTC, fetzi commented
@freekmurze if fixed all comments from your review.

2017-06-14 14:50 UTC, freekmurze approved these changes

2017-06-14 14:50 UTC, freekmurze commented
Ok for me, thanks

@sebastiandedeyne will take care of this further.

2017-06-14 17:08 UTC, sebastiandedeyne requested changes
Big thanks for this! I posted a few more change requests, when these are done I'll pull this in!

2017-06-14 17:08 UTC, sebastiandedeyne commented on config/mailable-test.php
> +    'base_namespace' => 'App\Mails',
Can this be changed to `App\Mail`? (sorry, was wrong in the original issue)

2017-06-14 17:08 UTC, sebastiandedeyne commented on src/MailableFactory.php
> +            $mailableClass = sprintf('%s\\%s', config('mailable-test.base_namespace'), $mailableClass);
Is this necessary? We're already doing a `class_exists` in `SendTestMail`, can't we normalize the class name there so this class doesn't care about resolving the base namespace?

2017-06-14 20:30 UTC, fetzi commented
@sebastiandedeyne done, I've also removed the `MailableDoesNotExist` exception class.

2017-06-15 06:25 UTC, merged

2017-06-15 06:26 UTC, sebastiandedeyne commented
Thanks! Released as `v1.1`